version: "3.7"

services:
  redis:
    image: redis
    container_name: my_redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - new_net

  springboot:
    image: slothst/github_actions_demo
    container_name: springboot
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - new_net

networks:
  new_net:
    driver: bridge
    external: true
