version: "3.7"

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
  springboot:
    container_name: springboot
    image: slothst/github-actions-demo
    build:
      context: .
#      dockerfile: ./Dockerfile
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
