spring:
  #
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    # jdbc:h2:mem:test
    url: ${datasource_URL}
    username: ${datasource_NAME}
    password: ${datasource_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql